BUGFIX: if gr1c missing, provide minimum version
Before this changeset, if gr1c was missing, the error message to be
printed referred to an undefined variable, hence the exception:

	'`gr1c >= {v}` not found in the PATH.\n'.format(v=v) +
    NameError: global name 'v' is not defined

This changeset replaces `v` with GR1C_MIN_VERSION.