TST: use `pytest`, instead of `nose`
for compatibility with Python 3.10.
The package `nose` is not compatible with Python 3.10,
because it imports abstract base classes from the
module `collections`,

[`nose == 1.3.7`](https://pypi.org/project/nose/1.3.7/#history)
imports in Python 3.10 without error, but `nosetests` fails,
due to imports from the module `collections` of classes that
have moved to the module `collections.abc`. The error raised contains:

```
  File ".../.virtualenvs/.../lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
```

Relevant information about CPython changes in `collections` (removal of
ABCs):
- https://github.com/python/cpython/pull/23754
- https://bugs.python.org/issue37324
- https://docs.python.org/3.10/library/collections.abc.html#collections-abstract-base-classes
- Deprecation since Python 3.3, present until Python 3.9:
      https://docs.python.org/3.9/library/collections.html#module-collections
- Removed in Python 3.10:
      https://docs.python.org/3.10/whatsnew/3.10.html#removed

The script `run_tests.py` is rewritten, based on `pytest` functionality.

The file `test/transys_mathset_test.py` has been changed to mode 100644
in order to not need an equivalent `pytest` option for option `--exe`
of `nose`.

In the test script `tests/mathfunc_test.py`, the function
`_get_state_input_output_pair_test` has been renamed to
`_get_state_input_output_pair` to avoid its name being matched by the
pattern `python_functions = test_* *_test` defined in the
configuration file `tests/pytest.ini`.