BUG: use `io.BytesIO`, instead of `io.StringIO`
following changes to Python. The method `pydot.Dot.create_png`
wraps the method `pydot.Dot.create`, and is dynamically created
inside the method `pydot.Dot.__init__` upon instantiation.
On Python 3, the method `pydot.Dot.create` returns a `bytes` object.

Before this commit, calling the function
`tulip.transys.export.graph2dot.plot_pydot` from outside
an `ipython` shell resulted in the exception (excerpt):

```
  File ".../tulip/transys/export/graph2dot.py", line 564, in plot_pydot
    sio.write(png_str)
TypeError: string argument expected, got 'bytes'
```

https://docs.python.org/3/library/io.html#io.BytesIO
https://docs.python.org/3/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit